import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers'

import SidBar from "../components/SidBar";
import ThemeContext from "@/contexts/ThemeContext";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeContext>


            <div className="flex h-screen w-full overflow-hidde ">
              <div className="w-[18%]">
                <SidBar />
              </div>
              <div className="w-[82%] flex flex-1 flex-col overflow-hidden ">
                <main className="flex-1 overflow-y-auto p-3 bg-gray-100 ">
                  {children}
                </main>
              </div>

            </div>
          </ThemeContext>

        </Providers>
      </body>
    </html>
  );
}
