import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers'

import SidBar from "../components/SidBar";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex h-screen w-full overflow-hidde">
            <div className="w-[20%]">
              <SidBar />
            </div>
            <div className="w-[80%] flex flex-1 flex-col overflow-hidden ">
                 <main className="flex-1 overflow-y-auto p-3 bg-gray-100">
                    {children}
                </main>
            </div>

          </div>

        </Providers>
      </body>
    </html>
  );
}
